### PR TITLE
Dropdown

### PR DESCRIPTION
**Pull request by cdalangin**
added the drop down menu!

### CODE REVIEW

**Review by KohinaTheCat — CHANGES_REQUESTED** [review]
Is it possible to have the drop-down show under the profile icon? Also can you merge this with the latest change in main. It has the fix for the login, logout, login issue.

**Comment by cdalangin** [comment]
> Is it possible to have the drop-down show under the profile icon? Also can you merge this with the latest change in main. It has the fix for the login, logout, login issue.

okie gotcha.. should i merge this version first or make the changes?

**Review by KohinaTheCat — APPROVED** [review]
Nice drop down!

**Comment by cdalangin** [comment]
thank!

**Pull request merged**
