### PR TITLE
Heat map

### LINKED ISSUE #19: Heatmap
Using: 
- **day.js**
- **react-grid-heatmap**

### LINKED ISSUE #28: Heat-map date axis shows the wrong month
image

### PR DESCRIPTION
**Pull request by pablomdd**
Heat map working and add to G Calendar
- Add react-grid-heatmap package
- Add dayjs package
- Add date-io package #26 

image

### CODE REVIEW

**Comment by zhangshyue** [comment]
Could you merge it with main first?

**Review by zhangshyue — APPROVED** [review]

**Comment by KohinaTheCat** [comment]
image

**Review by KohinaTheCat — COMMENTED** [review]
image

**Review by KohinaTheCat — APPROVED** [review]
Looks good guys! Ready to merge?

**Review by KohinaTheCat — APPROVED** [review]
nice fix for #28

**Pull request merged**
